feat: Add error handling to release download process.
This commit adds a check to see if the downloaded release exists and, if not, outputs a relevant error message to the console and exits the process with status 1. The commit also updates the message outputs to reflect the result of the download process.

diff --git a/.github/downloadReleaseFiles/action.yaml b/.github/downloadReleaseFiles/action.yaml
--- a/.github/downloadReleaseFiles/action.yaml
+++ b/.github/downloadReleaseFiles/action.yaml
@@ -28,11 +28,16 @@ runs:
         echo "pattern: $PATTERN"
         mkdir -pv upload-dir/${{ inputs.release_tag }}
         echo "Start to download release files from MaaRelease..."
-        gh release download ${{ inputs.release_tag }} --repo 'MaaAssistantArknights/MaaRelease' --pattern "$PATTERN" --clobber --dir upload-dir/${{ inputs.release_tag }}
+        gh release download ${{ inputs.release_tag }} --repo 'MaaAssistantArknights/MaaRelease' --pattern "$PATTERN" --clobber --dir upload-dir/${{ inputs.release_tag }} || echo "Release ${{ inputs.release_tag }} not found in MaaRelease"
         echo "Start to download release files from MaaAssistantArknights..."
-        gh release download ${{ inputs.release_tag }} --repo 'MaaAssistantArknights/MaaAssistantArknights' --pattern "$PATTERN" --clobber --dir upload-dir/${{ inputs.release_tag }}
-        echo "Done, folder view:"
-        ls -lhA upload-dir/${{ inputs.release_tag }}
+        gh release download ${{ inputs.release_tag }} --repo 'MaaAssistantArknights/MaaAssistantArknights' --pattern "$PATTERN" --clobber --dir upload-dir/${{ inputs.release_tag }} || echo "Release ${{ inputs.release_tag }} not found in MaaAssistantArknights"
+        if [ -d "upload-dir/${{ inputs.release_tag }}" ] && [ "$(ls -A "upload-dir/${{ inputs.release_tag }}")" ]; then
+          echo "Done, folder view:"
+          ls -lhA upload-dir/${{ inputs.release_tag }}
+        else
+          echo "Failed, no release downloaded."
+          exit 1
+        fi
 
 outputs:
   dir:
